{
 "title": "M",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Facteur de puissance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "queryText": "SELECT \n  strftime('%s', timestamp) AS time,\n  facteur_puissance as value\nFROM mesures \norder by time",
     "rawQueryText": "SELECT \n  strftime('%s', timestamp) AS time,\n  facteur_puissance as value\nFROM mesures \norder by time",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Energie (Wh)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "queryText": "SELECT \n  strftime('%s', timestamp)  AS \"time\",\n  energie \nFROM mesures \nWHERE courant IS NOT NULL \nORDER BY timestamp ASC\n",
     "rawQueryText": "SELECT \n  strftime('%s', timestamp)  AS \"time\",\n  energie \nFROM mesures \nWHERE courant IS NOT NULL \nORDER BY timestamp ASC\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Courant (A)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\n  timestamp AS \"time\",\n  courant\nFROM\n  mesures\nORDER BY\n  timestamp ASC\n",
     "rawQueryText": "SELECT\n  timestamp AS \"time\",\n  courant\nFROM\n  mesures\nORDER BY\n  timestamp ASC\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Tension (V)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT \n  strftime('%Y-%m-%dT%H:%M:%S', timestamp)  AS \"time\",\n  tension \nFROM mesures \nORDER BY timestamp ASC\n",
     "rawQueryText": "SELECT \n  strftime('%Y-%m-%dT%H:%M:%S', timestamp)  AS \"time\",\n  tension \nFROM mesures \nORDER BY timestamp ASC\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Puissance (W)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "queryText": "SELECT \n  strftime('%s', timestamp) AS time,\n  puissance as value\nFROM mesures \norder by time\n",
     "rawQueryText": "SELECT \n  strftime('%s', timestamp) AS time,\n  puissance as value\nFROM mesures \norder by time\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}