{
 "title": "Daschboard IOT",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Puissance (W)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"electric_data\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r._measurement == \"mesures\")\r\n  |> filter(fn: (r) => r._field == \"puissance\")"
    }
   ]
  },
  {
   "title": "Energie (Wh)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"electric_data\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r._measurement == \"mesures\")\r\n  |> filter(fn: (r) => r._field == \"energie\")"
    }
   ]
  },
  {
   "title": "Facteur de puissance",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"electric_data\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r._measurement == \"mesures\")\r\n  |> filter(fn: (r) => r._field == \"facteur_puissance\")"
    }
   ]
  },
  {
   "title": "Courant (A)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"electric_data\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r._measurement == \"mesures\")\r\n  |> filter(fn: (r) => r._field == \"courant\")"
    }
   ]
  },
  {
   "title": "Tension (V)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"electric_data\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r._measurement == \"mesures\")\r\n  |> filter(fn: (r) => r._field == \"tension\")"
    }
   ]
  }
 ]
}